### ISSUE TITLE
Add CLI for converting between GeoTIFF / ArcASCII and NetCDF

### ISSUE THREAD

**Issue by brendan-ward** [consbio/clover#11]

**Comment by brendan-ward** [comment]
Ideally this should be able to handle sources in ArcASCII too, but will likely need to provide a source CRS.

**Comment by brendan-ward** [comment]
For GeoTIFF / ArcASCII, it may be appropriate to specify a format string with a time dimension to help make stacking along a time dimension cleaner.

E.g., instead of a wildcard for datasets, we could so something like:

```
> clover  convert  foo_{year}.asc  foo.nc 
```

which we could then use to find all files w/ ```glob``` using ```foo_*.asc```, parse out the year from each filename and put them in ascending order, create a time dimension, and iterate over these to stack data along that time dimension.

**Comment by kennino** [comment]
This would be very handy. We (the CBI climate team) have typically just used ad-hoc scripts to do this because of things that tend to vary from case to case (and because we haven't needed it often enough to build a proper tool):

- specifying the calendar and units attribute of the time coordinate variable (data can be annual, monthly, daily, other, and cf conventions allow various ways of specifying dates)
- specifying the variable type (double, float, packed short)
- inconsistencies (due mostly to our own laziness) in metadata to be included in NetCDF attributes
- projections

So there's probably a fair bit of configurability one would want with such a tool.

**Comment by brendan-ward** [comment]
```to_netcdf``` command handles this now, and covers most of the options listed by @kennino 

Currently allows any raster input that ```rasterio``` can read; assumes single-band input datasets.

If a wildcard filename pattern is used, it allows either stacking directly to a dimension but no coordinate variable (stacked in order files are listed from directory):

```> clover to_netcdf ppt_*.asc ppt.nc ppt --src-crs EPSG:4326```

or when years are part of the filename:

```> clover to_netcdf ppt_%Y.asc ppt.nc ppt --src-crs EPSG:4326```

Would allow for files named ```ppt_2010.asc``` ... ```ppt_2100.asc``` to be stacked (in ascending order) with a CF convention ```time``` dimension and coordinate variable (in units of days since first year in this series).  Days and months could be added later.

Metadata is intentionally left out right now; that should be handled elsewhere.
